workspace:
  path: /saleor
pipeline:
  startSlack:
    image: plugins/slack
    channel: jenkins
    secrets: [slack_webhook]
    username: drone
    icon_url: https://avatars2.githubusercontent.com/u/2181346?s=200&v=4
    template: >
      *start* building *{{repo.name}}* <${DRONE_BUILD_LINK}|#{{build.number}}>.
      Someone gave *{{build.branch}}* a little push.
    when:
      event: [push]
      branch: [dev, master]

  restoreCache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./.yarn-cache
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
    when:
      event: [push]
      branch: [dev, master]

  getSaleorDevConfig:
    image: gcr.io/mirrormedia-1470651750304/drone-cloud-sdk:latest
    secrets: [google_credentials]
    commands:
      - gcloud source repos clone configs ../configs --project mirrormedia-1470651750304
      - ls ../configs
      - mkdir configs
      - cp ../configs/mirror-media/saleor-mirror/dev/.kube.yml .kube.yml
      - rm -rf ../configs
    when:
      event: [push]
      branch: [master, dev]

  buildSaleorThenPublish:
    image: plugins/gcr
    repo: mirrormedia-1470651750304/${DRONE_REPO_NAME}
    tag: ${DRONE_BRANCH}_${DRONE_COMMIT_AUTHOR}_${DRONE_BUILD_NUMBER}_saleor-mirror
    secrets: [google_credentials]
    when:
      event: [push]
      branch: [dev, master]

  deploySaleorDev:
    image: nytimes/drone-gke
    zone: asia-east1-a
    cluster: dev
    namespace: default
    verbose: true
    secrets:
      - source: google_credentials
        target: token
    vars:
      image: gcr.io/mirrormedia-1470651750304/${DRONE_REPO_NAME}:${DRONE_BRANCH}_${DRONE_COMMIT_AUTHOR}_${DRONE_BUILD_NUMBER}_saleor-mirror
      app: ${DRONE_REPO_NAME}
      tier: backend
    when:
      event: [push]
      branch: [dev, master]

  rebuildCache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./.yarn-cache
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
    when:
      branch: [dev, master]

  finishSlack:
    image: plugins/slack
    channel: jenkins
    secrets: [slack_webhook]
    username: drone
    icon_url: https://avatars2.githubusercontent.com/u/2181346?s=200&v=4
    when:
      status: [success, failure]
      event: [push]
      branch: [dev, master]
    template: >
      {{#success build.status}}
        *success* ${DRONE_REPO_NAME}:${DRONE_BRANCH}_${DRONE_COMMIT_AUTHOR}_${DRONE_BUILD_NUMBER} was well served.
        Check out our new <http://104.155.209.114/graphql |Saleor Backend>.
      {{else}}
        Houston, we have a problem. Build <${DRONE_BUILD_LINK}|#{{build.number}}> failed.
      {{/success}}
